name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env_file: .env.production
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
      
      redis:
        image: redis
        ports:
          - 6379:6379

      keycloak:
        image: quay.io/keycloak/keycloak
        env_file: .env.production
        ports:
          - 8080:8080
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8080/auth"]
          interval: 10s
          timeout: 5s
          retries: 5

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: cd code && yarn install

      - name: Start application
        run: yarn start &
        env:
          NODE_ENV: production

      - name: Run tests
        run: yarn test

      - name: Shut down Docker containers
        run: docker-compose down

