name: CD

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/resumeai:latest .
          docker tag your-dockerhub-username/resumeai:latest your-dockerhub-username/resumeai:latest
          docker push your-dockerhub-username/resumeai:latest

      # Deploy application on server
      - name: Deploy Application
        run: |
          ssh user@server-ip << 'EOF'
            docker pull your-dockerhub-username/resumeai:latest
            docker stop resumeai || true
            docker rm resumeai || true
            docker run -d --name resumeai -p 3000:3000 --env-file .env your-dockerhub-username/resumeai:latest
          EOF
